#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. script/homebrew
. script/cask

# move to script/rbenv
#rbenv install 1.9.3-p194
#rbenv global 1.9.3-p194
#rbenv rehash

rake install

#. osx/set-defaults.sh
