#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade


# Install grc and coreutils
#brew install grc coreutils

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

brew install rbenv
brew install rbenv-gemset
brew install ruby-build
#brew install postgresql
echo "run 'brew info postgresql' to see postgresql installation instructions."
echo "typically, you'll want to do:"
echo "initdb /usr/local/var/postgres -E utf8"
echo "To load on login:"
echo " mkdir -p ~/Library/LaunchAgents"
echo " cp /usr/local/Cellar/postgresql/9.2.1/homebrew.mxcl.postgresql.plist ~/Library/LaunchAgents/"
echo " launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
echo "to start manually:"
echo " pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"

# or maybe with 
#Success. You can now start the database server using:
#
#    postgres -D /usr/local/var/postgres
#or
#    pg_ctl -D /usr/local/var/postgres -l logfile start




brew install ack
brew install tree
brew install webkit2png

#brew install libiconv 
brew install imagemagick 
brew install libpng 
brew install cmake 
brew install ghostscript 
brew install jasper 
brew install redis 
brew install ctags 


brew cleanup


